import { FIREBASE_READY, db, collection, query, orderBy, limit, getDocs, addDoc, serverTimestamp } from './firebase.js';

const GAME_ID = 'neon-run';
const NAME_KEY = 'dl_guest_name_v1', BEST_KEY = 'dl_neon_best_v1', SETTINGS_KEY = 'dl_settings_v1', RATE_KEY = 'dl_score_rate_v1';
const canvas = document.getElementById('gameCanvas'), ctx = canvas.getContext('2d');
const $ = id => document.getElementById(id);
let W=900,H=390,dpr=1, raf=0, last=0, running=false, paused=false, gameOver=false, score=0, speed=1, distance=0, spawnIn=1.1, submitted=false;
let player={x:115,y:0,w:30,h:30,vy:0,onGround:false,rot:0};
let obstacles=[], particles=[], stars=[];
let best=Number(localStorage.getItem(BEST_KEY)||0);

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function initials(n){return (n||'G').trim().slice(0,2).toUpperCase();}
function getName(){return localStorage.getItem(NAME_KEY)||'';}
function guest(){return 'Guest_'+Math.floor(1000+Math.random()*9000);}
const banned=/\b(?:fuck|shit|bitch|asshole|cunt|nigger|faggot|porn|dick|pussy)\b/i;
function validName(n){return /^[A-Za-z0-9_ .-]{2,16}$/.test(n)&&!banned.test(n);}
function showToast(msg){const t=$('toast');t.textContent=msg;t.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.hidden=true,2800);}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=Math.max(320,r.width);H=Math.max(300,r.height);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);player.x=Math.min(115,W*.18);}
function ground(){return H-62;}
function setupStars(){stars=Array.from({length:70},()=>({x:Math.random()*W,y:Math.random()*(H*.72),r:Math.random()*1.7+.3,a:Math.random()*.7+.2,s:Math.random()*.25+.05}));}
function reset(){cancelAnimationFrame(raf);running=false;paused=false;gameOver=false;score=0;speed=1;distance=0;spawnIn=.9;obstacles=[];particles=[];player={x:Math.min(115,W*.18),y:ground()-30,w:30,h:30,vy:0,onGround:true,rot:0};$('score').textContent='0';$('speed').textContent='1.0×';$('runState').textContent='READY';$('startOverlay').classList.remove('hidden');$('gameOverOverlay').classList.add('hidden');$('scoreBtn').disabled=false;submitted=false;draw();}
function jump(){if(gameOver){start();return} if(!running){start();return} if(paused){paused=false;$('runState').textContent='RUNNING';last=performance.now();raf=requestAnimationFrame(loop);return} if(player.onGround){player.vy=-780;player.onGround=false;burst(player.x+15,ground()-4,8);}}
function start(){reset();running=true;$('startOverlay').classList.add('hidden');$('runState').textContent='RUNNING';last=performance.now();raf=requestAnimationFrame(loop);}
function end(){running=false;gameOver=true;cancelAnimationFrame(raf);best=Math.max(best,Math.floor(score));localStorage.setItem(BEST_KEY,best);$('bestScore').textContent=best.toLocaleString();$('finalScore').textContent=Math.floor(score).toLocaleString();$('finalBest').textContent=best.toLocaleString();$('runState').textContent='CRASHED';$('gameOverOverlay').classList.remove('hidden');burst(player.x+15,player.y+15,28);draw();}
function spawn(){const h=26+Math.random()*35,w=18+Math.random()*24;const type=Math.random()<.22?'tall':'spike';obstacles.push({x:W+30,y:ground()-h,w,h,type,phase:Math.random()*6});spawnIn=Math.max(.48, .95-speed*.055+Math.random()*.62);}
function burst(x,y,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*250,vy:(Math.random()-.8)*260,life:.5+Math.random()*.45,r:1+Math.random()*3});}
function update(dt){speed=Math.min(2.65,1+distance/1150);distance+=dt*100*speed;score=Math.floor(distance/7);$('score').textContent=score.toLocaleString();$('speed').textContent=speed.toFixed(1)+'×';spawnIn-=dt;if(spawnIn<=0)spawn();player.vy+=2050*dt;player.y+=player.vy*dt;player.rot+=dt*7;if(player.y+player.h>=ground()){player.y=ground()-player.h;player.vy=0;player.onGround=true;player.rot=Math.round(player.rot/(Math.PI/2))*Math.PI/2;} for(const o of obstacles)o.x-=430*speed*dt;obstacles=obstacles.filter(o=>o.x+o.w>-20);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);for(const o of obstacles){if(player.x+5<o.x+o.w&&player.x+player.w-5>o.x&&player.y+5<o.y+o.h&&player.y+player.h-4>o.y){end();return;}}}
function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0b1020');g.addColorStop(1,'#07090f');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const s of stars){s.x-=s.s; if(s.x<0)s.x=W;ctx.globalAlpha=s.a;ctx.fillStyle='#dbe7ff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.strokeStyle='rgba(124,92,255,.13)';ctx.lineWidth=1;for(let x=0;x<W;x+=55){ctx.beginPath();ctx.moveTo(x,ground());ctx.lineTo(x-100,H);ctx.stroke();}ctx.fillStyle='#0d1320';ctx.fillRect(0,ground(),W,H-ground());ctx.fillStyle='#7c5cff';ctx.fillRect(0,ground(),W,2);for(const o of obstacles){ctx.save();ctx.translate(o.x,o.y);if(o.type==='spike'){ctx.fillStyle='#ff4f8b';ctx.shadowColor='#ff4f8b';ctx.shadowBlur=15;ctx.beginPath();ctx.moveTo(0,o.h);ctx.lineTo(o.w/2,0);ctx.lineTo(o.w,o.h);ctx.closePath();ctx.fill();}else{ctx.fillStyle='#00d9ff';ctx.shadowColor='#00d9ff';ctx.shadowBlur=15;ctx.fillRect(0,0,o.w,o.h);ctx.fillStyle='#07111a';ctx.fillRect(5,5,o.w-10,5);}ctx.restore();}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#00d9ff';ctx.fillRect(p.x,p.y,p.r,p.r);}ctx.globalAlpha=1;ctx.save();ctx.translate(player.x+15,player.y+15);ctx.rotate(player.rot);ctx.shadowColor='#7c5cff';ctx.shadowBlur=22;ctx.fillStyle='#f4f7ff';ctx.fillRect(-15,-15,30,30);ctx.shadowBlur=0;ctx.fillStyle='#7c5cff';ctx.fillRect(-9,-9,7,7);ctx.fillStyle='#00d9ff';ctx.fillRect(2,-9,7,7);ctx.fillStyle='#080b12';ctx.fillRect(-8,4,16,4);ctx.restore();}
function loop(now){if(!running)return;const dt=Math.min(.032,(now-last)/1000);last=now;if(!paused)update(dt);draw();raf=requestAnimationFrame(loop);}
function togglePause(){if(!running||gameOver)return;paused=!paused;$('runState').textContent=paused?'PAUSED':'RUNNING';if(!paused){last=performance.now();raf=requestAnimationFrame(loop);}}
async function submitScore(){if(submitted)return;const n=Math.floor(score);if(n<1){showToast('Get a score first.');return}const now=Date.now();let attempts=JSON.parse(localStorage.getItem(RATE_KEY)||'[]').filter(t=>now-t<60000);if(attempts.length>=5){showToast('Score submissions are cooling down.');return}if(!FIREBASE_READY||!db){showToast('Leaderboard backend is not configured yet.');return}const name=getName();if(!validName(name)){showToast('Your display name needs a quick fix.');openNameModal();return}attempts.push(now);localStorage.setItem(RATE_KEY,JSON.stringify(attempts));$('scoreBtn').disabled=true;try{await addDoc(collection(db,'scores'),{game_id:GAME_ID,player_name:name,score:n,timestamp:serverTimestamp()});submitted=true;showToast('Score submitted 🏆');renderBoard();}catch(e){$('scoreBtn').disabled=false;showToast('Could not submit score.');console.error(e);}}
async function renderBoard(){const board=$('board');if(!FIREBASE_READY||!db){board.innerHTML='<div class="board-empty">Leaderboard backend not configured.</div>';return}board.innerHTML='<div class="board-loading">Loading rankings…</div>';try{const snap=await getDocs(query(collection(db,'scores'),orderBy('score','desc'),limit(50)));const rows=snap.docs.map(d=>d.data()).filter(x=>x.game_id===GAME_ID).slice(0,10);if(!rows.length){board.innerHTML='<div class="board-empty">No scores yet. You have the deeply inconvenient opportunity to be first. 👑</div>';return}$('statHigh').textContent=Number(rows[0].score||0).toLocaleString();$('statPlayers').textContent=rows.length.toLocaleString();board.innerHTML=rows.map((r,i)=>`<div class="row"><div class="rank ${i<3?'gold':''}">${['🥇','🥈','🥉'][i]||'#'+(i+1)}</div><div class="row-name"><span class="avatar">${esc(initials(r.player_name))}</span>${esc(r.player_name)}</div><div class="row-score">${Number(r.score||0).toLocaleString()}</div></div>`).join('');}catch(e){board.innerHTML='<div class="board-empty">Couldn’t load the leaderboard. Check the Firestore index/rules.</div>';console.error(e);}}
function openNameModal(){ $('nameModal').hidden=false;const input=$('nameInput');input.value=getName()||guest();setTimeout(()=>input.focus(),50);}
function ensureName(){if(getName()){$('navName').textContent=getName();$('navAvatar').textContent=initials(getName());return}openNameModal();}
$('nameForm').addEventListener('submit',e=>{e.preventDefault();const n=$('nameInput').value.trim();$('nameError').textContent='';if(!validName(n)){$('nameError').textContent='Use 2–16 letters, numbers, spaces, dots, dashes, or underscores. No profanity.';return}localStorage.setItem(NAME_KEY,n);$('navName').textContent=n;$('navAvatar').textContent=initials(n);$('nameModal').hidden=true;showToast('Handle saved. Now go cause problems.');});
$('playHero').onclick=()=>{$('game').scrollIntoView({behavior:'smooth'});setTimeout(()=>start(),350)};$('startBtn').onclick=start;$('restartBtn').onclick=start;$('scoreBtn').onclick=submitScore;$('refreshBoard').onclick=renderBoard;$('canvasWrap').addEventListener('pointerdown',e=>{if(e.target===canvas||e.target.closest('.canvas-wrap'))jump()});window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();jump()}else if(e.code==='Escape')togglePause();else if(e.key.toLowerCase()==='r')start();});window.addEventListener('resize',()=>{resize();setupStars();draw();});
(function init(){resize();setupStars();$('year').textContent=new Date().getFullYear();$('bestScore').textContent=best.toLocaleString();ensureName();renderBoard();draw();})();
